apply plugin: "java"

repositories {
    mavenCentral()
    maven {
        url "https://maven.top-q.co.il/content/repositories/public/"
    }
    maven {
        // some old dependencies for hive
        url "https://repo.huaweicloud.com/repository/maven/huaweicloudsdk/"
    }
}

dependencies {
    implementation(project(':pxf-api'))
    implementation(project(':pxf-hbase'))
    implementation(project(':pxf-hdfs'))
    implementation(project(':pxf-hive'))

//    implementation 'org.xerial.snappy:snappy-java:1.1.10.4'
//    implementation 'org.apache.httpcomponents:httpclient:4.5.13'
    implementation 'org.jsystemtest:jsystemCore:6.1.05'
    implementation 'org.jsystemtest.systemobjects:cli:6.0.01'
//    implementation 'org.mockito:mockito-core:1.10.19'
//    implementation 'ch.ethz.ganymed:ganymed-ssh2:261'
    implementation 'org.postgresql:postgresql:42.7.2' // fixme version!
////    implementation 'org.springframework:spring:2.5.6'
////    providedCompile 'org.springframework:spring-web:5.3.33'
//    implementation 'net.sf.opencsv:opencsv:2.3'
    implementation 'ant:ant-junit:1.6.5'
    implementation 'org.apache.ant:ant:1.10.11'
    implementation 'org.awaitility:awaitility:4.2.0'
//    implementation 'com.amazonaws:aws-java-sdk-s3:1.12.261'
//    implementation 'com.fasterxml.jackson.core:jackson-core:2.12.6'
//    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.4.2'
//    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.12.6'
//    implementation 'org.apache.httpcomponents:httpcore:4.4.14'
//    implementation 'com.google.cloud.bigdataoss:gcs-connector:hadoop2-1.9.17:shaded'
//    implementation 'com.microsoft.azure:azure-data-lake-store-sdk:2.2.3'
//    implementation 'com.microsoft.azure:azure-storage:5.5.0'
    implementation("org.apache.hadoop:hadoop-common")                { transitive = false }
//    implementation "org.apache.hadoop:hadoop-aws:2.10.2"
//    implementation "org.apache.hadoop:hadoop-azure:2.10.2"
//    implementation "org.apache.hadoop:hadoop-azure-datalake:2.10.2"
//    implementation "org.apache.hadoop:hadoop-auth:2.10.2"
//    implementation "org.apache.hadoop:hadoop-mapreduce-client-core:2.10.2"
//    implementation "org.apache.hadoop:hadoop-annotations:2.10.2"
//    implementation "org.apache.hadoop:hadoop-hdfs:2.10.2"
    implementation "org.apache.avro:avro-tools:1.7.7"
    implementation( "org.apache.hbase:hbase-common")
    implementation( "org.apache.hbase:hbase-protocol")
    implementation( "org.apache.hbase:hbase-client")
    implementation( "org.apache.hbase:hbase-thrift:${hbaseVersion}")
    implementation( "org.apache.hbase:hbase-server:${hbaseVersion}")
//    implementation 'org.pentaho:pentaho-aggdesigner-algorithm:5.1.5-jhyde'

    implementation( "org.apache.hive:hive-exec")
    implementation("org.apache.hive:hive-service")
    implementation( "org.apache.hive:hive-metastore")
    implementation( "org.apache.hive:hive-common")
    implementation( "org.apache.hive:hive-serde")
    implementation( "org.apache.hive:hive-jdbc")
//    implementation "org.apache.orc:orc-core:1.6.13"
    testImplementation "org.mockito:mockito-all:1.9.5"
    testImplementation 'junit:junit:4.13.1'
//    testImplementation 'org.powermock:powermock-module-testng:1.6.4'
//    testImplementation 'org.powermock:powermock-api-mockito:1.6.4'
    implementation 'org.testng:testng:6.8.7'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

test {
    useTestNG()
    testLogging {
        events "failed"
    }
}