
dependencies {
    // AthenaJDBC42.jar
    implementation 'com.clickhouse:clickhouse-jdbc:0.6.1'
    // clickhouse-jdbc-0.6.1-http.jar ??
    // commons-cli-1.5.0.jar ??

    implementation 'org.apache.httpcomponents.client5:httpclient5:5.3.1'

    // DB2
    implementation 'net.sf.jt400:jt400:11.2'

    // MSSQL
    implementation 'com.microsoft.sqlserver:mssql-jdbc:8.2.2.jre11'

    // MySQL
    implementation 'com.mysql:mysql-connector-java:8.0.26'

    // Snowflake
    implementation 'net.snowflake:snowflake-jdbc:3.13.9'

    // MDB-26167 - ORA
    implementation 'com.oracle.database.jdbc:ojdbc11:23.3.0.23.09'
    implementation 'com.oracle.database.jdbc:ucp11:23.3.0.23.09'
    // orai18n - unknown version


    // MDB-20944 - trino
    testImplementation 'io.trino:trino-jdbc:403'

}