name: pxf
on:
  push:
    paths:
      - 'server/**'
    branches:
      - main
  pull_request:
    paths:
      - 'server/**'

jobs:
  build-and-test:
    name: build-and-test with java v${{ matrix.Java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'corretto'
      - name: Assemble and test with Gradle
        working-directory: ./server
        run: ./gradlew build --no-daemon